//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCB2.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("610, 110")]
        public global::System.Drawing.Size QuestListSize {
            get {
                return ((global::System.Drawing.Size)(this["QuestListSize"]));
            }
            set {
                this["QuestListSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string QuestListColumnWidth {
            get {
                return ((string)(this["QuestListColumnWidth"]));
            }
            set {
                this["QuestListColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250, 188")]
        public global::System.Drawing.Size ShipDetailSize {
            get {
                return ((global::System.Drawing.Size)(this["ShipDetailSize"]));
            }
            set {
                this["ShipDetailSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ShipDetailColumnWidth {
            get {
                return ((string)(this["ShipDetailColumnWidth"]));
            }
            set {
                this["ShipDetailColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0, 0, 0")]
        public global::System.Drawing.Rectangle ShipListBounds {
            get {
                return ((global::System.Drawing.Rectangle)(this["ShipListBounds"]));
            }
            set {
                this["ShipListBounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ShipListColumnWidth {
            get {
                return ((string)(this["ShipListColumnWidth"]));
            }
            set {
                this["ShipListColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ItemListColumnWidth {
            get {
                return ((string)(this["ItemListColumnWidth"]));
            }
            set {
                this["ItemListColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0, 0, 0")]
        public global::System.Drawing.Rectangle ItemListBounds {
            get {
                return ((global::System.Drawing.Rectangle)(this["ItemListBounds"]));
            }
            set {
                this["ItemListBounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0, 0, 0")]
        public global::System.Drawing.Rectangle LogFormBounds {
            get {
                return ((global::System.Drawing.Rectangle)(this["LogFormBounds"]));
            }
            set {
                this["LogFormBounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LogItemColumnWidth {
            get {
                return ((string)(this["LogItemColumnWidth"]));
            }
            set {
                this["LogItemColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LogShipColumnWidth {
            get {
                return ((string)(this["LogShipColumnWidth"]));
            }
            set {
                this["LogShipColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LogBattleColumnWidth {
            get {
                return ((string)(this["LogBattleColumnWidth"]));
            }
            set {
                this["LogBattleColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LogMissionColumnWidth {
            get {
                return ((string)(this["LogMissionColumnWidth"]));
            }
            set {
                this["LogMissionColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LogMaterialColumnWidth {
            get {
                return ((string)(this["LogMaterialColumnWidth"]));
            }
            set {
                this["LogMaterialColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0, 0, 0")]
        public global::System.Drawing.Rectangle BattleDetailBounds {
            get {
                return ((global::System.Drawing.Rectangle)(this["BattleDetailBounds"]));
            }
            set {
                this["BattleDetailBounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BattleDetailColumnWidth {
            get {
                return ((string)(this["BattleDetailColumnWidth"]));
            }
            set {
                this["BattleDetailColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OnlineLogEndpoint {
            get {
                return ((string)(this["OnlineLogEndpoint"]));
            }
            set {
                this["OnlineLogEndpoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OnlineLogSecurityToken {
            get {
                return ((string)(this["OnlineLogSecurityToken"]));
            }
            set {
                this["OnlineLogSecurityToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8088")]
        public int ProxyPort {
            get {
                return ((int)(this["ProxyPort"]));
            }
            set {
                this["ProxyPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("26")]
        public int HPThreshold {
            get {
                return ((int)(this["HPThreshold"]));
            }
            set {
                this["HPThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VerboseStatus {
            get {
                return ((bool)(this["VerboseStatus"]));
            }
            set {
                this["VerboseStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseLogWindow {
            get {
                return ((bool)(this["UseLogWindow"]));
            }
            set {
                this["UseLogWindow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.dmm.com/netgame/social/-/gadgets/=/app_id=854854/")]
        public string GadgetURI {
            get {
                return ((string)(this["GadgetURI"]));
            }
            set {
                this["GadgetURI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShipListVisible {
            get {
                return ((bool)(this["ShipListVisible"]));
            }
            set {
                this["ShipListVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ItemListVisible {
            get {
                return ((bool)(this["ItemListVisible"]));
            }
            set {
                this["ItemListVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LogWndVisible {
            get {
                return ((bool)(this["LogWndVisible"]));
            }
            set {
                this["LogWndVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point MainFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["MainFormLocation"]));
            }
            set {
                this["MainFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ImageStoreDir {
            get {
                return ((string)(this["ImageStoreDir"]));
            }
            set {
                this["ImageStoreDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SyncronizeTimerProcess {
            get {
                return ((bool)(this["SyncronizeTimerProcess"]));
            }
            set {
                this["SyncronizeTimerProcess"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LogStoreDir {
            get {
                return ((string)(this["LogStoreDir"]));
            }
            set {
                this["LogStoreDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FiddlerOverrideGateway {
            get {
                return ((string)(this["FiddlerOverrideGateway"]));
            }
            set {
                this["FiddlerOverrideGateway"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint LogStoreType {
            get {
                return ((uint)(this["LogStoreType"]));
            }
            set {
                this["LogStoreType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GSRefreshToken {
            get {
                return ((string)(this["GSRefreshToken"]));
            }
            set {
                this["GSRefreshToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HideHeader {
            get {
                return ((bool)(this["HideHeader"]));
            }
            set {
                this["HideHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("49")]
        public int CondCeil {
            get {
                return ((int)(this["CondCeil"]));
            }
            set {
                this["CondCeil"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("火力,対空,装甲,雷装,HP,燃料,装備")]
        public string ShipDetailItem {
            get {
                return ((string)(this["ShipDetailItem"]));
            }
            set {
                this["ShipDetailItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SuppressSuceedWriteLog {
            get {
                return ((bool)(this["SuppressSuceedWriteLog"]));
            }
            set {
                this["SuppressSuceedWriteLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseMasterDataView {
            get {
                return ((bool)(this["UseMasterDataView"]));
            }
            set {
                this["UseMasterDataView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MasterDataWndVisible {
            get {
                return ((bool)(this["MasterDataWndVisible"]));
            }
            set {
                this["MasterDataWndVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MasterShipColumnWidth {
            get {
                return ((string)(this["MasterShipColumnWidth"]));
            }
            set {
                this["MasterShipColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0, 0, 0")]
        public global::System.Drawing.Rectangle MasterListBounds {
            get {
                return ((global::System.Drawing.Rectangle)(this["MasterListBounds"]));
            }
            set {
                this["MasterListBounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MasterSlotItemColumnWidth {
            get {
                return ((string)(this["MasterSlotItemColumnWidth"]));
            }
            set {
                this["MasterSlotItemColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SlotItemListVisible {
            get {
                return ((bool)(this["SlotItemListVisible"]));
            }
            set {
                this["SlotItemListVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0, 0, 0")]
        public global::System.Drawing.Rectangle SlotItemListBounds {
            get {
                return ((global::System.Drawing.Rectangle)(this["SlotItemListBounds"]));
            }
            set {
                this["SlotItemListBounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SlotItemListColumnWidth {
            get {
                return ((string)(this["SlotItemListColumnWidth"]));
            }
            set {
                this["SlotItemListColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MasterShipTypeColumnWidth {
            get {
                return ((string)(this["MasterShipTypeColumnWidth"]));
            }
            set {
                this["MasterShipTypeColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseDevMenu {
            get {
                return ((bool)(this["UseDevMenu"]));
            }
            set {
                this["UseDevMenu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int SkipbackJSON {
            get {
                return ((int)(this["SkipbackJSON"]));
            }
            set {
                this["SkipbackJSON"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MuteOnMinimize {
            get {
                return ((bool)(this["MuteOnMinimize"]));
            }
            set {
                this["MuteOnMinimize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HideDroppedShip {
            get {
                return ((bool)(this["HideDroppedShip"]));
            }
            set {
                this["HideDroppedShip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("43FC22576EE7869657B54662FB9759FD")]
        public string WithdrawalKey {
            get {
                return ((string)(this["WithdrawalKey"]));
            }
            set {
                this["WithdrawalKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowEnemyBattleStatus {
            get {
                return ((bool)(this["ShowEnemyBattleStatus"]));
            }
            set {
                this["ShowEnemyBattleStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SuppressBrowserDialog {
            get {
                return ((bool)(this["SuppressBrowserDialog"]));
            }
            set {
                this["SuppressBrowserDialog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UpstreamProxyHost {
            get {
                return ((string)(this["UpstreamProxyHost"]));
            }
            set {
                this["UpstreamProxyHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8080")]
        public decimal UpstreamProxyPort {
            get {
                return ((decimal)(this["UpstreamProxyPort"]));
            }
            set {
                this["UpstreamProxyPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseUpstreamProxy {
            get {
                return ((bool)(this["UseUpstreamProxy"]));
            }
            set {
                this["UseUpstreamProxy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NotificationServer {
            get {
                return ((string)(this["NotificationServer"]));
            }
            set {
                this["NotificationServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NotifyFinishBattle {
            get {
                return ((bool)(this["NotifyFinishBattle"]));
            }
            set {
                this["NotifyFinishBattle"] = value;
            }
        }
    }
}
